--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Ubuntu 17.0-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dwash; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dwash;


ALTER SCHEMA dwash OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: brand; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand (
    brand_id integer NOT NULL,
    brand_name_ar character varying,
    brand_name_en character varying,
    brand_descriptions_ar character varying,
    brand_descriptions_en character varying,
    brand_logo character varying,
    brand_backgroun_image character varying,
    brand_artist_first_name_ar character varying,
    brand_artist_father_name_ar character varying,
    brand_artist_last_name_ar character varying,
    brand_artist_first_name_en character varying,
    brand_artist_father_name_en character varying,
    brand_artist_last_name_en character varying,
    brand_status integer,
    brand_country_id integer,
    brand_city_id integer,
    brand_ur_id integer,
    brand_district_id integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.brand OWNER TO postgres;

--
-- Name: brand_brand_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand ALTER COLUMN brand_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_history; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_history (
    hist_brand_hist_id integer NOT NULL,
    hist_brand_id integer,
    hist_brand_name_ar character varying,
    hist_brand_name_en character varying,
    hist_brand_descriptions_ar character varying,
    hist_brand_descriptions_en character varying,
    hist_brand_logo character varying,
    hist_brand_backgroun_image character varying,
    hist_brand_artist_first_name_ar character varying,
    hist_brand_artist_father_name_ar character varying,
    hist_brand_artist_last_name_ar character varying,
    hist_brand_artist_first_name_en character varying,
    hist_brand_artist_father_name_en character varying,
    hist_brand_artist_last_name_en character varying,
    hist_brand_status integer,
    hist_brand_country_id integer,
    hist_brand_city_id integer,
    hist_brand_ur_id integer,
    hist_brand_district_id integer,
    hist_brand_created_on timestamp without time zone
);


ALTER TABLE dwash.brand_history OWNER TO postgres;

--
-- Name: brand_history_hist_brand_hist_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_history ALTER COLUMN hist_brand_hist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_history_hist_brand_hist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_notification; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_notification (
    notification_id bigint NOT NULL,
    notification_title_en character varying NOT NULL,
    notification_description_en character varying,
    read smallint DEFAULT 0,
    brand_id integer NOT NULL,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    request_id bigint,
    notification_title_ar character varying,
    notification_description_ar character varying
);


ALTER TABLE dwash.brand_notification OWNER TO postgres;

--
-- Name: brand_notification_notification_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_notification ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_notification_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_social_media; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_social_media (
    smedia_id integer NOT NULL,
    smedia_media_id integer,
    smedia_brand_id integer,
    smedia_brand_url character varying,
    smedia_status integer,
    smedia_ur_id integer,
    smedia_created_on timestamp without time zone,
    smedia_update_on timestamp without time zone
);


ALTER TABLE dwash.brand_social_media OWNER TO postgres;

--
-- Name: brand_social_media_history; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_social_media_history (
    hist_smedia_hist_id integer NOT NULL,
    hist_smedia_id integer,
    hist_smedia_media_id integer,
    hist_smedia_brand_id integer,
    hist_smedia_brand_url character varying,
    hist_smedia_ur_id integer,
    hist_smedia_status integer,
    hist_smedia_created_on timestamp without time zone
);


ALTER TABLE dwash.brand_social_media_history OWNER TO postgres;

--
-- Name: brand_social_media_history_hist_smedia_hist_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_social_media_history ALTER COLUMN hist_smedia_hist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_social_media_history_hist_smedia_hist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_social_media_smedia_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_social_media ALTER COLUMN smedia_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_social_media_smedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_social_media_temp; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_social_media_temp (
    tmp_smedia_tmp_id integer NOT NULL,
    tmp_smedia_id integer,
    tmp_smedia_rq_id integer,
    tmp_smedia_media_id integer,
    tmp_smedia_brand_id integer,
    tmp_smedia_brand_url character varying,
    tmp_smedia_status integer,
    tmp_smedia_ur_id integer,
    tmp_smedia_created_on timestamp without time zone
);


ALTER TABLE dwash.brand_social_media_temp OWNER TO postgres;

--
-- Name: brand_social_media_temp_tmp_smedia_tmp_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_social_media_temp ALTER COLUMN tmp_smedia_tmp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_social_media_temp_tmp_smedia_tmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_temp; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_temp (
    tmp_brand_tmp_id integer NOT NULL,
    tmp_brand_id integer,
    tmp_brand_rq_id integer,
    tmp_brand_name_ar character varying,
    tmp_brand_name_en character varying,
    tmp_brand_descriptions_ar character varying,
    tmp_brand_descriptions_en character varying,
    tmp_brand_logo character varying,
    tmp_brand_backgroun_image character varying,
    tmp_brand_artist_first_name_ar character varying,
    tmp_brand_artist_father_name_ar character varying,
    tmp_brand_artist_last_name_ar character varying,
    tmp_brand_artist_first_name_en character varying,
    tmp_brand_artist_father_name_en character varying,
    tmp_brand_artist_last_name_en character varying,
    tmp_brand_status integer,
    tmp_brand_country_id integer,
    tmp_brand_city_id integer,
    tmp_brand_ur_id integer,
    tmp_brand_district_id integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.brand_temp OWNER TO postgres;

--
-- Name: brand_temp_tmp_brand_tmp_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_temp ALTER COLUMN tmp_brand_tmp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_temp_tmp_brand_tmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_wallet; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_wallet (
    wll_id integer NOT NULL,
    wll_brand_id integer,
    wll_iban character varying,
    wll_bank_account_number character varying,
    wll_bank_certificate character varying,
    wll_bank_id integer,
    wll_total_ammount integer,
    wll_deduction_prs integer,
    wll_reject_total_fine integer,
    wll_transfer_date timestamp without time zone,
    wll_ur_id integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    wll_bank_name character varying
);


ALTER TABLE dwash.brand_wallet OWNER TO postgres;

--
-- Name: brand_wallet_history; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_wallet_history (
    hist_wll_hist_id integer NOT NULL,
    hist_wll_id integer,
    hist_wll_brand_id integer,
    hist_wll_iban character varying,
    hist_wll_bank_account_number integer,
    hist_wll_bank_certificate character varying,
    hist_wll_bank_id integer,
    hist_wll_total_ammount integer,
    hist_wll_deduction_prs integer,
    hist_wll_reject_total_fine integer,
    hist_wll_transfer_date timestamp without time zone,
    hist_wll_ur_id integer,
    hist_wll_update_on timestamp without time zone
);


ALTER TABLE dwash.brand_wallet_history OWNER TO postgres;

--
-- Name: brand_wallet_history_hist_wll_hist_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_wallet_history ALTER COLUMN hist_wll_hist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_wallet_history_hist_wll_hist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_wallet_temp; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.brand_wallet_temp (
    tmp_wll_id integer NOT NULL,
    tmp_wll_brand_id integer,
    tmp_wll_iban character varying,
    tmp_wll_bank_account_number character varying,
    tmp_wll_bank_certificate character varying,
    tmp_wll_bank_id integer,
    tmp_wll_total_ammount integer,
    tmp_wll_deduction_prs integer,
    tmp_wll_reject_total_fine integer,
    tmp_wll_ur_id integer,
    tmp_wll_transfer_date timestamp without time zone,
    last_updated_on timestamp without time zone,
    created_on timestamp without time zone,
    tmp_wll_bank_name character varying
);


ALTER TABLE dwash.brand_wallet_temp OWNER TO postgres;

--
-- Name: brand_wallet_temp_tmp_wll_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_wallet_temp ALTER COLUMN tmp_wll_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_wallet_temp_tmp_wll_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_wallet_wll_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.brand_wallet ALTER COLUMN wll_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.brand_wallet_wll_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: confirmation_codes; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.confirmation_codes (
    code_id integer NOT NULL,
    number character varying NOT NULL,
    trials_number integer,
    confirmation_code character varying NOT NULL,
    is_consumed boolean,
    created_on timestamp without time zone
);


ALTER TABLE dwash.confirmation_codes OWNER TO postgres;

--
-- Name: confirmation_codes_code_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.confirmation_codes ALTER COLUMN code_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.confirmation_codes_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discount; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.discount (
    discount_id integer NOT NULL,
    discount_code character varying NOT NULL,
    discount_status smallint NOT NULL,
    discount_type character varying NOT NULL,
    discount_amount real,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    brand character varying
);


ALTER TABLE dwash.discount OWNER TO postgres;

--
-- Name: discount_discount_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.discount ALTER COLUMN discount_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.discount_discount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extra_services; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.extra_services (
    extra_id integer NOT NULL,
    extra_name_ar character varying,
    extra_name_er character varying,
    extra_ur_id integer,
    extra_descriptions_ar character varying,
    extra_descriptions_en character varying,
    extra_price integer,
    extra_services_id integer,
    extra_status integer,
    extra_image character varying,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.extra_services OWNER TO postgres;

--
-- Name: extra_services_extra_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.extra_services ALTER COLUMN extra_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.extra_services_extra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extra_services_history; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.extra_services_history (
    hist_extra_hist_id integer NOT NULL,
    hist_extra_id integer,
    hist_extra_name_ar character varying,
    hist_extra_name_er character varying,
    hist_extra_ur_id integer,
    hist_extra_descriptions_ar character varying,
    hist_extra_descriptions_en character varying,
    hist_extra_price integer,
    hist_extra_services_id integer,
    hist_extra_status integer,
    hist_extra_image character varying,
    hist_created_at timestamp without time zone
);


ALTER TABLE dwash.extra_services_history OWNER TO postgres;

--
-- Name: extra_services_history_hist_extra_hist_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.extra_services_history ALTER COLUMN hist_extra_hist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.extra_services_history_hist_extra_hist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extra_services_temp; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.extra_services_temp (
    tmp_extra_tmp_id integer NOT NULL,
    tmp_extra_id integer,
    tmp_extra_rq_id integer,
    tmp_extra_name_ar character varying,
    tmp_extra_name_er character varying,
    tmp_extra_ur_id integer,
    tmp_extra_descriptions_ar character varying,
    tmp_extra_descriptions_en character varying,
    tmp_extra_price integer,
    tmp_extra_services_id integer,
    tmp_extra_status integer,
    tmp_extra_image character varying,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.extra_services_temp OWNER TO postgres;

--
-- Name: extra_services_temp_tmp_extra_tmp_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.extra_services_temp ALTER COLUMN tmp_extra_tmp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.extra_services_temp_tmp_extra_tmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: freelancer_balance; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.freelancer_balance (
    balance_id bigint NOT NULL,
    brand_id integer,
    invoice_id bigint,
    request_id bigint,
    total_amount double precision,
    deduction_prs integer,
    due_amount double precision,
    status character varying,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    deduction_amount double precision
);


ALTER TABLE dwash.freelancer_balance OWNER TO postgres;

--
-- Name: freelancer_balance_balance_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.freelancer_balance ALTER COLUMN balance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.freelancer_balance_balance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slots; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.slots (
    slot_id bigint NOT NULL,
    brand_id integer NOT NULL,
    time_from time without time zone NOT NULL,
    time_to time without time zone NOT NULL,
    reserved integer NOT NULL,
    consumer_id integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    reservation_date date,
    locked_date timestamp without time zone
);


ALTER TABLE dwash.slots OWNER TO postgres;

--
-- Name: freelancer_slots_slot_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.slots ALTER COLUMN slot_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.freelancer_slots_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.invoice (
    invoice_id integer NOT NULL,
    username character varying NOT NULL,
    total_amount double precision,
    status character varying,
    brand_id integer,
    request_id integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    slot_id bigint,
    discount_id integer,
    reviewed boolean DEFAULT false,
    discount_amount real,
    due_amount double precision
);


ALTER TABLE dwash.invoice OWNER TO postgres;

--
-- Name: invoice_invoice_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.invoice ALTER COLUMN invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.invoice_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_item; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.invoice_item (
    invoice_item_id integer NOT NULL,
    invoice_id integer,
    service_id integer,
    item_price real,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.invoice_item OWNER TO postgres;

--
-- Name: invoice_item_extra; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.invoice_item_extra (
    item_extra_id integer NOT NULL,
    extra_service_id integer,
    invoice_item_id integer,
    item_extra_price real,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.invoice_item_extra OWNER TO postgres;

--
-- Name: invoice_item_extra_item_extra_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.invoice_item_extra ALTER COLUMN item_extra_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.invoice_item_extra_item_extra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_item_invoice_item_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.invoice_item ALTER COLUMN invoice_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.invoice_item_invoice_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_bank; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_bank (
    bank_id integer NOT NULL,
    bank_name_ar character varying,
    bank_name_en character varying,
    bank_ur_id integer,
    bank_status integer
);


ALTER TABLE dwash.lu_bank OWNER TO postgres;

--
-- Name: lu_bank_bank_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_bank ALTER COLUMN bank_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_bank_bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_city; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_city (
    ct_id integer NOT NULL,
    ct_co_id integer,
    ct_ur_id integer,
    ct_name_ar character varying,
    ct_name_en character varying,
    ct_status integer,
    ct_created_on timestamp without time zone
);


ALTER TABLE dwash.lu_city OWNER TO postgres;

--
-- Name: lu_city_ct_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_city ALTER COLUMN ct_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_city_ct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_country; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_country (
    co_id integer NOT NULL,
    co_name_ar character varying,
    co_name_en character varying,
    co_ur_id integer,
    co_status integer,
    co_created_on timestamp without time zone
);


ALTER TABLE dwash.lu_country OWNER TO postgres;

--
-- Name: lu_country_co_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_country ALTER COLUMN co_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_country_co_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_district; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_district (
    dis_id integer NOT NULL,
    dis_ct_id integer,
    dis_ur_id integer,
    dis_name_ar character varying,
    dis_name_en character varying,
    dis_status integer,
    dis_created_on timestamp without time zone
);


ALTER TABLE dwash.lu_district OWNER TO postgres;

--
-- Name: lu_district_dis_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_district ALTER COLUMN dis_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_district_dis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_extra_services; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_extra_services (
    lextra_id integer NOT NULL,
    lextra_name_ar character varying,
    lextra_name_er character varying,
    lextra_ur_id integer,
    lextra_descriptions_ar character varying,
    lextra_descriptions_en character varying,
    lextra_status integer,
    created_at timestamp without time zone
);


ALTER TABLE dwash.lu_extra_services OWNER TO postgres;

--
-- Name: lu_extra_services_lextra_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_extra_services ALTER COLUMN lextra_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_extra_services_lextra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_identification_type; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_identification_type (
    identity_ty_id integer NOT NULL,
    identity_ty_name_ar character varying(100) NOT NULL,
    identity_ty_name_en character varying(100) NOT NULL,
    identity_ty_status integer
);


ALTER TABLE dwash.lu_identification_type OWNER TO postgres;

--
-- Name: lu_request; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_request (
    rq_id integer NOT NULL,
    rq_nmae_ar character varying,
    rq_name_en character varying,
    rq_ur_id integer,
    rq_code_category integer,
    rq_status integer,
    rq_created_on timestamp without time zone
);


ALTER TABLE dwash.lu_request OWNER TO postgres;

--
-- Name: lu_request_category; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_request_category (
    cat_id integer NOT NULL,
    cat_rq_id integer,
    cat_ur_id integer,
    cat_name_ar character varying,
    cat_name_en character varying,
    cat_status integer,
    car_created_on timestamp without time zone
);


ALTER TABLE dwash.lu_request_category OWNER TO postgres;

--
-- Name: lu_request_category_cat_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_request_category ALTER COLUMN cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_request_category_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_request_rq_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_request ALTER COLUMN rq_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_request_rq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_service_type; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_service_type (
    services_type_id integer NOT NULL,
    service_type_name_ar character varying,
    service_type_name_en character varying
);


ALTER TABLE dwash.lu_service_type OWNER TO postgres;

--
-- Name: lu_service_type_service_type_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_service_type ALTER COLUMN services_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_service_type_service_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lu_social_media; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.lu_social_media (
    media_id integer NOT NULL,
    media_name_ar character varying,
    media_name_en character varying,
    media_ur_id integer,
    media_logo character varying,
    media_status integer,
    media_created_at timestamp without time zone
);


ALTER TABLE dwash.lu_social_media OWNER TO postgres;

--
-- Name: lu_social_media_media_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.lu_social_media ALTER COLUMN media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.lu_social_media_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.payment (
    payment_id bigint NOT NULL,
    brand_id integer,
    total_amount double precision,
    payment_status character varying,
    user_id integer,
    invoice_id bigint,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    payment_method_id smallint
);


ALTER TABLE dwash.payment OWNER TO postgres;

--
-- Name: payment_method; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.payment_method (
    payment_method_id integer NOT NULL,
    payment_method_name character varying NOT NULL,
    payment_method_status smallint DEFAULT 0 NOT NULL
);


ALTER TABLE dwash.payment_method OWNER TO postgres;

--
-- Name: payment_payment_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.payment_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: request; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.request (
    rq_id integer NOT NULL,
    rq_code_id integer,
    rq_waiting_prosses_id integer,
    rq_status integer,
    rq_ur_id integer,
    last_updated_on timestamp without time zone,
    created_on timestamp without time zone,
    rq_status_name character varying
);


ALTER TABLE dwash.request OWNER TO postgres;

--
-- Name: request_rq_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.request ALTER COLUMN rq_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.request_rq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.reviews (
    review_id bigint NOT NULL,
    brand_id integer NOT NULL,
    request_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    username character varying NOT NULL,
    description text,
    appraisal smallint,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.reviews OWNER TO postgres;

--
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.reviews ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_images; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.service_images (
    id integer NOT NULL,
    image_path character varying,
    service_id integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.service_images OWNER TO postgres;

--
-- Name: service_temp_images; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.service_temp_images (
    id integer NOT NULL,
    service_id integer NOT NULL,
    image_path text NOT NULL,
    last_updated_on timestamp without time zone,
    created_on timestamp without time zone
);


ALTER TABLE dwash.service_temp_images OWNER TO postgres;

--
-- Name: service_images_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.service_temp_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.service_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_images_tmp_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.service_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.service_images_tmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_type; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.service_type (
    brand_id integer NOT NULL,
    service_type_id integer NOT NULL,
    service_type_status character varying
);


ALTER TABLE dwash.service_type OWNER TO postgres;

--
-- Name: services; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.services (
    services_id integer NOT NULL,
    services_name_ar character varying,
    services_name_er character varying,
    services_descriptions_ar character varying,
    services_descriptions_en character varying,
    services_brand_id integer,
    services_price integer,
    services_image character varying,
    services_type_id integer,
    services_ur_id integer,
    services_extar_lu integer,
    services_status integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.services OWNER TO postgres;

--
-- Name: services_history; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.services_history (
    hist_services_hist_id integer NOT NULL,
    hist_services_id integer,
    hist_services_name_ar character varying,
    hist_services_name_er character varying,
    hist_services_descriptions_ar character varying,
    hist_services_descriptions_en character varying,
    hist_services_brand_id integer,
    hist_services_price integer,
    hist_services_image character varying,
    hist_services_type_id integer,
    hist_services_ur_id integer,
    hist_services_extar_lu integer,
    hist_services_status integer,
    hist_services_created_on timestamp without time zone
);


ALTER TABLE dwash.services_history OWNER TO postgres;

--
-- Name: services_history_hist_services_hist_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.services_history ALTER COLUMN hist_services_hist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.services_history_hist_services_hist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_services_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.services ALTER COLUMN services_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.services_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_temp; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.services_temp (
    tmp_services_tmp_id integer NOT NULL,
    tmp_services_id integer,
    tmp_services_rq_id integer,
    tmp_services_name_ar character varying,
    tmp_services_name_er character varying,
    tmp_services_descriptions_ar character varying,
    tmp_services_descriptions_en character varying,
    tmp_services_brand_id integer,
    tmp_services_price integer,
    tmp_services_image character varying,
    tmp_services_type_id integer,
    tmp_services_ur_id integer,
    tmp_services_extar_lu integer,
    tmp_services_status integer,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone
);


ALTER TABLE dwash.services_temp OWNER TO postgres;

--
-- Name: services_temp_tmp_services_tmp_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.services_temp ALTER COLUMN tmp_services_tmp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.services_temp_tmp_services_tmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_type; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.services_type (
    stype_id integer NOT NULL,
    stype_name_ar character varying,
    stype_name_en character varying,
    stype_ur_id integer,
    stype_descriptions_ar character varying,
    stype_descriptions_en character varying,
    stype_status integer,
    stype_created_at timestamp without time zone
);


ALTER TABLE dwash.services_type OWNER TO postgres;

--
-- Name: services_type_history; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.services_type_history (
    hist_stype_hist_id integer NOT NULL,
    hist_stype_id integer,
    hist_stype_name_ar character varying,
    hist_stype_name_en character varying,
    hist_stype_ur_id integer,
    hist_stype_descriptions_ar character varying,
    hist_stype_descriptions_en character varying,
    hist_stype_status integer,
    hist_stype_created_at timestamp without time zone
);


ALTER TABLE dwash.services_type_history OWNER TO postgres;

--
-- Name: services_type_history_hist_stype_hist_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.services_type_history ALTER COLUMN hist_stype_hist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.services_type_history_hist_stype_hist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_type_stype_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.services_type ALTER COLUMN stype_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.services_type_stype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_type_temp; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.services_type_temp (
    tmp_stype_tmp_id integer NOT NULL,
    tmp_stype_id integer,
    tmp_stype_rq_id integer,
    tmp_stype_name_ar character varying,
    tmp_stype_name_en character varying,
    tmp_stype_ur_id integer,
    tmp_stype_descriptions_ar character varying,
    tmp_stype_descriptions_en character varying,
    tmp_stype_status integer,
    tmp_stype_created_at timestamp without time zone
);


ALTER TABLE dwash.services_type_temp OWNER TO postgres;

--
-- Name: services_type_temp_tmp_stype_tmp_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.services_type_temp ALTER COLUMN tmp_stype_tmp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.services_type_temp_tmp_stype_tmp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash."user" (
    ur_id integer NOT NULL,
    ur_user_name character varying,
    ur_email character varying,
    ur_identification_number character varying,
    ur_password character varying,
    ur_type integer,
    ur_name_ar character varying,
    ur_name_en character varying,
    ur_status integer,
    ur_agreement_accept integer,
    ur_created_on timestamp without time zone,
    ur_identification_type character varying,
    ur_identity_ty_id integer,
    ur_mobile character varying(100),
    ur_local character varying,
    ur_sex character varying,
    reset_password_date timestamp without time zone
);


ALTER TABLE dwash."user" OWNER TO postgres;

--
-- Name: user_address; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.user_address (
    user_address_id bigint NOT NULL,
    city_id integer NOT NULL,
    district_id integer NOT NULL,
    status smallint DEFAULT 0 NOT NULL,
    latitude character varying,
    longitude character varying,
    created_on timestamp without time zone,
    last_updated_on timestamp without time zone,
    ur_id bigint
);


ALTER TABLE dwash.user_address OWNER TO postgres;

--
-- Name: user_address_user_address_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.user_address ALTER COLUMN user_address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.user_address_user_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_hist; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.user_hist (
    hist_ur_id_hist integer NOT NULL,
    hist_ur_id integer,
    hist_ur_user_name character varying,
    hist_ur_email character varying,
    hist_ur_password character varying,
    hist_ur_type integer,
    hist_ur_name_ar character varying,
    hist_ur_name_en character varying,
    hist_ur_status integer,
    hist_ur_agreement_accept integer,
    hist_ur_created_on timestamp without time zone,
    hist_ur_identification_type character varying,
    hist_ur_identification_number character varying,
    hist_ur_identity_ty_id integer,
    hist_ur_mobile character varying(100)
);


ALTER TABLE dwash.user_hist OWNER TO postgres;

--
-- Name: user_hist_hist_ur_id_hist_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash.user_hist ALTER COLUMN hist_ur_id_hist ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.user_hist_hist_ur_id_hist_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_type; Type: TABLE; Schema: dwash; Owner: postgres
--

CREATE TABLE dwash.user_type (
    id integer NOT NULL,
    type character varying(20) NOT NULL
);


ALTER TABLE dwash.user_type OWNER TO postgres;

--
-- Name: user_ur_id_seq; Type: SEQUENCE; Schema: dwash; Owner: postgres
--

ALTER TABLE dwash."user" ALTER COLUMN ur_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dwash.user_ur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand_history brand_history_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_history
    ADD CONSTRAINT brand_history_pkey PRIMARY KEY (hist_brand_hist_id);


--
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (brand_id);


--
-- Name: brand_social_media_history brand_social_media_history_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_social_media_history
    ADD CONSTRAINT brand_social_media_history_pkey PRIMARY KEY (hist_smedia_hist_id);


--
-- Name: brand_social_media brand_social_media_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_social_media
    ADD CONSTRAINT brand_social_media_pkey PRIMARY KEY (smedia_id);


--
-- Name: brand_social_media_temp brand_social_media_temp_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_social_media_temp
    ADD CONSTRAINT brand_social_media_temp_pkey PRIMARY KEY (tmp_smedia_tmp_id);


--
-- Name: brand_temp brand_temp_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_temp
    ADD CONSTRAINT brand_temp_pkey PRIMARY KEY (tmp_brand_tmp_id);


--
-- Name: brand_wallet_history brand_wallet_history_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_wallet_history
    ADD CONSTRAINT brand_wallet_history_pkey PRIMARY KEY (hist_wll_hist_id);


--
-- Name: brand_wallet brand_wallet_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_wallet
    ADD CONSTRAINT brand_wallet_pkey PRIMARY KEY (wll_id);


--
-- Name: brand_wallet_temp brand_wallet_temp_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_wallet_temp
    ADD CONSTRAINT brand_wallet_temp_pkey PRIMARY KEY (tmp_wll_id);


--
-- Name: discount discount_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.discount
    ADD CONSTRAINT discount_pk PRIMARY KEY (discount_id);


--
-- Name: discount discount_unique; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.discount
    ADD CONSTRAINT discount_unique UNIQUE (discount_code);


--
-- Name: extra_services_history extra_services_history_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.extra_services_history
    ADD CONSTRAINT extra_services_history_pkey PRIMARY KEY (hist_extra_hist_id);


--
-- Name: extra_services extra_services_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.extra_services
    ADD CONSTRAINT extra_services_pkey PRIMARY KEY (extra_id);


--
-- Name: extra_services_temp extra_services_temp_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.extra_services_temp
    ADD CONSTRAINT extra_services_temp_pkey PRIMARY KEY (tmp_extra_tmp_id);


--
-- Name: freelancer_balance freelancer_balance_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.freelancer_balance
    ADD CONSTRAINT freelancer_balance_pk PRIMARY KEY (balance_id);


--
-- Name: slots freelancer_slots_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.slots
    ADD CONSTRAINT freelancer_slots_pk PRIMARY KEY (slot_id);


--
-- Name: invoice_item_extra invoice_item_extra_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.invoice_item_extra
    ADD CONSTRAINT invoice_item_extra_pk PRIMARY KEY (item_extra_id);


--
-- Name: invoice invoice_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.invoice
    ADD CONSTRAINT invoice_pk PRIMARY KEY (invoice_id);


--
-- Name: lu_bank lu_bank_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_bank
    ADD CONSTRAINT lu_bank_pkey PRIMARY KEY (bank_id);


--
-- Name: lu_city lu_city_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_city
    ADD CONSTRAINT lu_city_pkey PRIMARY KEY (ct_id);


--
-- Name: lu_country lu_country_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_country
    ADD CONSTRAINT lu_country_pkey PRIMARY KEY (co_id);


--
-- Name: lu_district lu_district_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_district
    ADD CONSTRAINT lu_district_pkey PRIMARY KEY (dis_id);


--
-- Name: lu_extra_services lu_extra_services_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_extra_services
    ADD CONSTRAINT lu_extra_services_pkey PRIMARY KEY (lextra_id);


--
-- Name: lu_identification_type lu_identification_type_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_identification_type
    ADD CONSTRAINT lu_identification_type_pkey PRIMARY KEY (identity_ty_id);


--
-- Name: lu_request_category lu_request_category_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_request_category
    ADD CONSTRAINT lu_request_category_pkey PRIMARY KEY (cat_id);


--
-- Name: lu_request lu_request_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_request
    ADD CONSTRAINT lu_request_pkey PRIMARY KEY (rq_id);


--
-- Name: lu_service_type lu_service_type_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_service_type
    ADD CONSTRAINT lu_service_type_pk PRIMARY KEY (services_type_id);


--
-- Name: lu_social_media lu_social_media_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.lu_social_media
    ADD CONSTRAINT lu_social_media_pkey PRIMARY KEY (media_id);


--
-- Name: invoice_item newtable_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.invoice_item
    ADD CONSTRAINT newtable_pk PRIMARY KEY (invoice_item_id);


--
-- Name: brand_notification notification_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.brand_notification
    ADD CONSTRAINT notification_pk PRIMARY KEY (notification_id);


--
-- Name: payment_method payment_method_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.payment_method
    ADD CONSTRAINT payment_method_pk PRIMARY KEY (payment_method_id);


--
-- Name: payment payment_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.payment
    ADD CONSTRAINT payment_pk PRIMARY KEY (payment_id);


--
-- Name: request request_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.request
    ADD CONSTRAINT request_pkey PRIMARY KEY (rq_id);


--
-- Name: reviews reviews_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.reviews
    ADD CONSTRAINT reviews_pk PRIMARY KEY (review_id);


--
-- Name: service_temp_images service_images_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.service_temp_images
    ADD CONSTRAINT service_images_pkey PRIMARY KEY (id);


--
-- Name: service_images service_images_tmp_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.service_images
    ADD CONSTRAINT service_images_tmp_pk PRIMARY KEY (id);


--
-- Name: service_type service_type_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.service_type
    ADD CONSTRAINT service_type_pk PRIMARY KEY (brand_id, service_type_id);


--
-- Name: services_history services_history_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.services_history
    ADD CONSTRAINT services_history_pkey PRIMARY KEY (hist_services_hist_id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (services_id);


--
-- Name: services_temp services_temp_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.services_temp
    ADD CONSTRAINT services_temp_pkey PRIMARY KEY (tmp_services_tmp_id);


--
-- Name: services_type_history services_type_history_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.services_type_history
    ADD CONSTRAINT services_type_history_pkey PRIMARY KEY (hist_stype_hist_id);


--
-- Name: services_type services_type_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.services_type
    ADD CONSTRAINT services_type_pkey PRIMARY KEY (stype_id);


--
-- Name: services_type_temp services_type_temp_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.services_type_temp
    ADD CONSTRAINT services_type_temp_pkey PRIMARY KEY (tmp_stype_tmp_id);


--
-- Name: user_address user_address_pk; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.user_address
    ADD CONSTRAINT user_address_pk PRIMARY KEY (user_address_id);


--
-- Name: user_hist user_hist_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.user_hist
    ADD CONSTRAINT user_hist_pkey PRIMARY KEY (hist_ur_id_hist);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (ur_id);


--
-- Name: user_type user_type_pkey; Type: CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash.user_type
    ADD CONSTRAINT user_type_pkey PRIMARY KEY (id);


--
-- Name: fki_user_type_fk; Type: INDEX; Schema: dwash; Owner: postgres
--

CREATE INDEX fki_user_type_fk ON dwash."user" USING btree (ur_type);


--
-- Name: user user_type_fk; Type: FK CONSTRAINT; Schema: dwash; Owner: postgres
--

ALTER TABLE ONLY dwash."user"
    ADD CONSTRAINT user_type_fk FOREIGN KEY (ur_type) REFERENCES dwash.user_type(id) NOT VALID;


--
-- PostgreSQL database dump complete
--
